---
dependency:
  name: galaxy
  options:
    role-files: requirements.yml

driver:
  name: docker

platforms:
  - name: domoticz-Debian9
    image: lansible/debian:stretch
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/lib/systemd/systemd"
    env:
      container: docker
    stop_signal: SIGRTMIN+3
    groups:
      - default

provisioner:
  name: ansible
  # log: true
  inventory:
    links:
      group_vars: group_vars/
      host_vars: host_vars/
  playbooks:
    create: ../ressources/create.yml
    prepare: ../ressources/prepare.yml
    converge: ../ressources/playbook.yml
  options:
    vvv: true

scenario:
  name: stable
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
