---
- name: "update apt cache"
  apt:
    update_cache: yes
  tags:
    - domoticz
    - installation
    - prerequisites

- name: "install prerequisites package"
  apt:
    name: "{{ domoticz_prerequisites }}"
    state: present
  tags:
    - domoticz
    - installation
    - prerequisites