---
- name: Converge
  hosts: all
  tasks:
    - name: "deploy domoticz"
      import_role:
        name: ansible-domoticz

  post_tasks:
    - name: Wait for Domoticz to succesfully restart
      wait_for:
        port: "{{ domoticz_port }}"

    - name: Test Domoticz HTTP webinterface
      uri:
        url: "http://{{ inventory_hostname }}:{{ domoticz_port }}"

    - name: Wait for Domoticz to succesfully restart
      wait_for:
        port: "{{ domoticz_https_port }}"
      when: domoticz_https

    - name: Test Domoticz HTTPS webinterface
      uri:
        url: "https://{{ inventory_hostname }}:{{ domoticz_https_port }}"
        validate_certs: false
      when: domoticz_https
