---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: "install systemd"
      apt:
        name:
          - systemd
          - systemd-sysv
        update_cache: true
        state: present

    - name: "remove unwanted systemd"
      systemd:
        name: "{{ item }}"
        masked: true
      with_items:
        - dev-hugepages.mount
        - sys-fs-fuse-connections.mount
