---
dependency:
  name: galaxy
  options:
    role-files: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-files: rules/yaml-lint.yml

platforms:
  - name: domoticz-Debian9
    image: debian:stretch

provisioner:
  name: ansible
  config_options:
    defaults:
  lint:
    name: ansible-lint
    options:
      vvv: true
      # c: rules/ansible-lint.yml
  